# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNFileSelector' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for RNFileSelector
  pod 'FileBrowser', :git => 'https://github.com/crutchcorn/FileBrowser.git', :branch => 'master'
end
